update

diff --git a/work b/work
--- a/work
+++ b/work
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 # Variables
-semester_path="/Users/maxinimus/Documents/university/3_year/2_semester"
-resume_path="/Users/maxinimus/Documents/resume"
+semester_path="$HOME/Documents/university/ms_year/1_semester"
+#semester_path="$HOME/Documents/university/3_year/2_semester"
+resume_path="$HOME/Documents/resume"
 default_latex_file_to_edit="content.tex"
 fallback_latex_file="main.tex"
 default_typst_file_to_edit="main.typ"
@@ -30,7 +31,7 @@ resume_flag=false
 grr_flag=false
 typst_flag=false
 latex_flag=false
-dir_semester=false
+dir_semester_flag=false
 
 # Verbose mode
 verbose=false
@@ -86,8 +87,18 @@ choose_course() {
 # Individual handler functions
 handle_flag_create() {
   # make it so that . is a valid argument, create a new directory here
+  if [ "$verbose" = true ]; then
+    echo "---- Creating new homework folder: Function called ----"
+  fi
+
   choose_course || { echo "Error choosing course"; return 1; } 
   cd "$semester_path/$course" || { echo "Error: Failed to change directory to $semester_path/$course"; return 1; }
+  if [ ! -d "hw" ]; then
+    if [ "$verbose" = true ]; then
+      echo "Creating hw directory"
+    fi
+    mkdir "hw" || { echo "Error: Failed to create hw directory"; return 1; }
+  fi
   cd "hw" || { echo "Error: Failed to change directory to hw"; return 1; }
   get_latest_hw
   previous_hw=$latest_hw
@@ -105,17 +116,57 @@ handle_flag_create() {
   mkdir "$latest_hw"
   cd "$latest_hw"
 
+  # --------------------
+  # if neither latex nor typst flag is set, set the flag based on the file type in previous homework
+  if [ "$typst_flag" = false ] && [ "$latex_flag" = false ]; then
+    if [[ -n "$(find "../$previous_hw" -maxdepth 1 -type f -name '*.typ' -print -quit 2>/dev/null)" ]]; then
+      if [ "$verbose" = true ]; then
+        echo "No flags set, defaulting to Typst because .typ file found."
+      fi
+      typst_flag=true
+    elif [[ -n "$(find "../$previous_hw" -maxdepth 1 -type f -name '*.tex' -print -quit 2>/dev/null)" ]]; then
+      if [ "$verbose" = true ]; then
+        echo "No flags set, defaulting to LaTeX because .tex file found."
+      fi
+      latex_flag=true
+    else
+      echo "Error: No .typ or .tex files found in previous homework, defaulting to typst."
+      typst_flag=true
+    fi
+  fi
+  if [ "$typst_flag" = true ]; then
+    handle_flag_typst
+  fi
+  if [ "$latex_flag" = true ]; then
+    handle_flag_latex
+  fi
+  # --------------------
+
   if [[ $latest_hw = "hw01" ]]; then
     if [ "$verbose" = true ]; then
       echo "Copying $fallback_file_to_edit from home directory"
     fi
-    cp "~/.$fallback_file_to_edit" $fallback_file_to_edit
-  else
-    if [ "$verbose" = true ]; then
-      echo "Copying $fallback_file_to_edit from $previous_hw"
+    cp "$HOME/.$fallback_file_to_edit" $fallback_file_to_edit
+    # if typst, also copy the default typst file
+    if [ "$latex_flag" = false ]; then
+      if [ "$verbose" = true ]; then
+        echo "Copying $default_typst_file_to_edit from home directory"
+      fi
+      cp "$HOME/.$default_typst_file_to_edit" $default_typst_file_to_edit
     fi
-    cp "../$previous_hw/$fallback_file_to_edit" $fallback_file_to_edit || { echo "Error copying $fallback_file_to_edit"; return 1; }
-
+  else
+    if [ ! -f "../$previous_hw/$fallback_file_to_edit" ]; then
+      if [ "$verbose" = true ]; then
+        echo "Copying $fallback_file_to_edit from home directory"
+      fi
+      cp "$HOME/.$fallback_file_to_edit" $fallback_file_to_edit
+    else
+      if [ "$verbose" = true ]; then
+        echo "Copying $fallback_file_to_edit from $previous_hw"
+      fi
+      cp "../$previous_hw/$fallback_file_to_edit" $fallback_file_to_edit
+    fi
+    
     # Replace the homework number in the title
     file=""
     pattern=""
@@ -124,10 +175,18 @@ handle_flag_create() {
       touch $default_latex_file_to_edit
 
       file=$fallback_latex_file
-      pattern="title{.* Homework .*}"
+      pattern="title{.*Homework .*}"
       matched_line=$(grep -o "$pattern" "$file")
     elif [ "$typst_flag" = true ]; then
-      cp "../$previous_hw/$default_typst_file_to_edit " $default_typst_file_to_edit || { echo "Error copying $default_typst_file_to_edit"; return 1; }
+      # if "../$previous_hw/$default_typst_file_to_edit" doesn't exist, copy from home directory
+      if [ ! -f "../$previous_hw/$default_typst_file_to_edit" ]; then
+        if [ "$verbose" = true ]; then
+          echo "Copying $default_typst_file_to_edit from home directory"
+        fi
+        cp "$HOME/.$default_typst_file_to_edit" $default_typst_file_to_edit
+      else
+        cp "../$previous_hw/$default_typst_file_to_edit" $default_typst_file_to_edit
+      fi
 
       file=$default_typst_file_to_edit
       pattern="title: \"Homework .*\","
@@ -160,15 +219,16 @@ handle_flag_create() {
     fi
   fi
 
+  if [ "$verbose" = true ]; then
+    echo "---- Creating new homework folder: Function ended successfully ----"
+  fi
+
   return 0;
 }
 
 handle_flag_change_dir() {
   # if argument is empty, just cd to the semester path
   # if semester flag is set, cd to the semester path
-  if [ "$dir_semester" = true ]; then
-    cd "$semester_path" || { echo "Error: Failed to change directory to $semester_path"; return 1; }
-  fi
   directory_to_cd="$first_argument"
 
   if [ "$verbose" = true ]; then
@@ -228,12 +288,12 @@ open_file_with_nvim() {
 get_latest_hw() {
   # Get the latest homework folder
   latest_hw=$(ls -d hw* 2>/dev/null | sort -n | tail -n 1)
-  if [ "$latest_hw" = "hw" ]; then
+
+  if [ "$latest_hw" = "" ]; then
     if [ "$verbose" = true ]; then
-      echo "No homework folders found"
+      echo "No homework folders found."
     fi
-    mkdir hw01
-    latest_hw="hw01"
+    return 1
   fi
   if [ "$verbose" = true ]; then
     echo "Latest homework folder: $latest_hw"
@@ -273,24 +333,30 @@ handle_flags() {
   if [ "$help_flag" = true ]; then
     echo "Help flag is set. Displaying help information."
     # Display help information here
-    echo "Usage: script.sh [options] [argument 1] [argument 2]"
+    echo "Usage: work [options] [argument 1] [argument 2]"
     echo "Options:"
     echo "  -h  Show help information"
     echo "  -c  Create a new homework folder at the course specified by the argument"
-    echo "  -d  Change directory to the specified course"
+    echo "  -d  Change directory relative to the current directory"
     echo "  -o  Force open the file. Used to open a file in the current directory. Can be used together with -d to both switch a directory and open the file"
     echo "  -f  Use fallback file to edit instead of the default file"
     echo "  -r  Open the resume directory. Can be used with -o to open the file in the resume directory"
-    echo "  -g  SSH into the server"
+    echo "  -s  Change directory relative to the semester path"
     echo "  -t  Use Typst"
     echo "  -l  Use LaTeX"
-    echo "  -s  Change directory to the semester path"
+    echo "  -g  SSH into the server"
     echo "  -v  Enable verbose mode"
     echo "Argument:"
     echo "  [argument 1]  The course name or path to change directory to"
     echo "  [argument 2]  The homework number to change directory to"
 
     return 0;
+  fi
+
+  # if both d and s flags are set, return an Error
+  if [ "$change_dir_flag" = true ] && [ "$dir_semester_flag" = true ]; then
+    echo "Error: Both change_dir and dir_semester_flag flags cannot be set at the same time."
+    return 1
   fi
 
   # if both typst_flag and latex_flag are set, return an Error
@@ -316,7 +382,7 @@ handle_flags() {
     handle_flag_latex
   fi
 
-  if $grr_flag; then
+  if [ "$grr_flag" = true ]; then
     handle_flag_grr || { echo "Error in handle_flag_grr"; return 1; }
     return 0;
   fi
@@ -324,8 +390,18 @@ handle_flags() {
   # could change resume flag to just use change dir but after changing argument
   $change_dir_flag && { handle_flag_change_dir || { echo "Error in handle_flag_change_dir"; return 1; }; }
 
-  if $resume_flag; then
+  if [ "$resume_flag" = true ]; then
     first_argument="$resume_path"
+    change_dir_flag=true
+    handle_flag_change_dir || { echo "Error in handle_flag_change_dir"; return 1; }
+  fi
+
+  if [ "$dir_semester_flag" = true ]; then
+    course=$(echo "$course_list" | grep -i "$first_argument")
+    if [ -n "$course" ]; then
+      first_argument=$course
+    fi
+    first_argument="$semester_path/$first_argument"
     change_dir_flag=true
     handle_flag_change_dir || { echo "Error in handle_flag_change_dir"; return 1; }
   fi
@@ -366,12 +442,12 @@ handle_flags() {
   if [ "$typst_flag" = false ] && [ "$latex_flag" = false ]; then
     if [[ -n "$(find . -maxdepth 1 -type f -name '*.typ' -print -quit 2>/dev/null)" ]]; then
       if [ "$verbose" = true ]; then
-        echo "No flags set, defaulting to Typst."
+        echo "No flags set, defaulting to Typst because .typ file found."
       fi
       typst_flag=true
     elif [[ -n "$(find . -maxdepth 1 -type f -name '*.tex' -print -quit 2>/dev/null)" ]]; then
       if [ "$verbose" = true ]; then
-        echo "No flags set, defaulting to LaTeX."
+        echo "No flags set, defaulting to LaTeX because .tex file found."
       fi
       latex_flag=true
     else
@@ -409,7 +485,7 @@ parse_flags() {
       g) grr_flag=true ;;
       t) typst_flag=true ;;
       l) latex_flag=true ;;
-      s) dir_semester=true ;;
+      s) dir_semester_flag=true ;;
       v) verbose=true ;;
       \?) echo "Invalid option"; return 1 ;;
     esac
@@ -430,7 +506,7 @@ parse_flags() {
     echo "grr_flag: $grr_flag"
     echo "typst_flag: $typst_flag"
     echo "latex_flag: $latex_flag"
-    echo "dir_semester: $dir_semester"
+    echo "dir_semester_flag: $dir_semester_flag"
     echo "---------------------"
   fi
 
@@ -466,7 +542,7 @@ main() {
   # Handle flags
   handle_flags || { echo "Error handling flags"; return 1; }
 
-  if [ "$help_flag" = true ]; then
+  if [ "$help_flag" = true ] || [ "$grr_flag" = true ]; then
     return 0
   fi
 
